package com.titanium.tielements;

public interface Constants {

    String MAIN_VIEW = "MAIN_VIEW";
    String STATUS_BAR_MENU_FRAGMENT = "STATUS_BAR_MENU_FRAGMENT";
    String NAV_BAR_MENU_FRAGMENT = "NAV_BAR_MENU_FRAGMENT";
    String QUICK_SETTINGS_MENU_FRAGMENT = "QUICK_SETTINGS_MENU_FRAGMENT";
    String RECENT_MENU_FRAGMENT = "RECENT_MENU_FRAGMENT";
    String LOCK_SCREEN_MENU_FRAGMENT = "LOCK_SCREEN_MENU_FRAGMENT";
    String SYSTEM_MENU_FRAGMENT = "SYSTEM_MENU_FRAGMENT";
}
