package com.titanium.tielements;

public interface Constants {

    String MAIN_VIEW = "MAIN_VIEW";
    String STATUS_BAR_MENU_FRAGMENT = "STATUS_BAR_MENU_FRAGMENT";
    String NAV_BAR_MENU_FRAGMENT = "NAV_BAR_MENU_FRAGMENT";
    String QUICK_SETTINGS_MENU_FRAGMENT = "QUICK_SETTINGS_MENU_FRAGMENT";
    String RECENT_MENU_FRAGMENT = "RECENT_MENU_FRAGMENT";
    String LOCK_SCREEN_MENU_FRAGMENT = "LOCK_SCREEN_MENU_FRAGMENT";
    String MISC_MENU_FRAGMENT = "MISC_MENU_FRAGMENT";
    String AMBIENT_MENU_FRAGMENT = "AMBIENT_MENU_FRAGMENT";
    String BATTERY_MENU_FRAGMENT = "BATTERY_MENU_FRAGMENT";
    String SCREEN_MENU_FRAGMENT = "SCREEN_MENU_FRAGMENT";
    String ANIMATION_MENU_FRAGMENT = "ANIMATION_MENU_FRAGMENT";
    String BUTTONS_MENU_FRAGMENT = "BUTTONS_MENU_FRAGMENT";
    String ABOUT_MENU_FRAGMENT = "ABOUT_MENU_FRAGMENT";
}
